# Generated by Django 3.2.7 on 2021-10-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpanel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
